# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - authoring-spotify

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://spotifyui.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9ef228e1d88b4e96abb63486ba99a420 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_46a4857e115f4155899bf885ae82a884 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: spotifyui.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9ef228e1d88b4e96abb63486ba99a420 }}/spotifyui:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'authoring-spotify'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f2e73e93a9a5480497019d11c80f9c54 }}
        images: 'spotifyui.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9ef228e1d88b4e96abb63486ba99a420 }}/spotifyui:${{ github.sha }}'